### ISSUE TITLE
Multiple Notification Windows ?

### ISSUE THREAD

**Issue by semmel** [pbojinov/nodeifications#10]
Hi,
awesome work!
Are there any plans to show several (e.g. the last 5) notification windows stacked under each other, like Chrome does? 
In this respect one should probably adopt the `tag` parameter from the [HTML5 Notification API (MDN)](https://developer.mozilla.org/en/docs/Web/API/notification) which controls whether the notification window replaces an existing one of the same tag or gets stacked below.
Perhaps it is insightful for others too, here is the comparison table with the HTML5 Api

| nw-desktop-notifications | HTML5 Api | HTML5 Api description |
| :-- | :-- | :-- |
| `title` | `title` | The title that must be shown within the notification |
| `message` | `body` | A string representing an extra content to display within the notification |
| `iconUrl` | `icon` | The URL of an image to be used as an icon by the notification |
|  | `dir` | `auto`, `ltr`, or `rtl` |
|  | `lang` | BCP 47 language tag e.g. "en-US" (?) |
|  | `tag` | An ID for a given notification that allows to retrieve, replace or remove it if necessary |
| `type` |  |  |
| `buttonPrimary` |  |  |
| `buttonSecondary` |  |  |
| `imageUrl` |  |  |
| `imageTitle` |  |  |

**Comment by pbojinov** [comment]
Hi @semmel, it currently isn't in the pipeline to stack multiple notifications but if this is something you are interested in taking on it would be a great addition to the project.

The API was initially modeled after the [https://developer.chrome.com/apps/notifications](Chrome Notifications API) to be an easy port from Chrome app to NWK app.

Originally I was envisioning only 3 notifications existing at once on screen and fading out based on some timer. Kind of how Chrome does it - https://chrome.google.com/webstore/detail/notification-api-sample/cndmbddaappldijonoekcdfdlhemhejm

Implementing the `tag` parameter from the HTML5 Notifications API looks like a good approach to stacking multiple notifications. 

Duration, notifications on screen, etc is all open to discussion.

**Comment by semmel** [comment]
Hi @pbojinov,
cool that you merged my changes :-)
Let me just make some brief remarks:

It was a wise choice to relate your work to the Rich Notifications in Chrome Apps [(chrome.notifications)](https://developer.chrome.com/apps/notifications), because that is what users may be familiar with.

One should keep the implemented features to a useful minimum. 
- Contrary to my previous post I think grouping multiple notifications with a `tag` is not really need in 90% of the use cases. The application could manage that itself.
- Even support for multiple notifications I do not consider very important.

The Api must be nice.
- The currently implemented all-purpose notification callback is ok. Perhaps an event emitter with events like `on_title`, `on_button_primary` could turn out more useful for the user of the library. Perhaps I could provide my implementation I use in production code here [semmel/PubSubJS](https://github.com/semmel/PubSubJS)
- I dont think generating _notification ids_ to manage multiple notifications as [chrome.notifications](https://developer.chrome.com/apps/notifications) does it is the right way. Instead I'd like to think that notifications are _objects_ and thus I'd prefer the way it is done in the [HTML5 Spec](https://developer.mozilla.org/en/docs/Web/API/notification) via Notification objects.

Considering new features I am intrigued by the `progress` type notification. But for that we'd need to have an `update` method too.

**Comment by pbojinov** [comment]
@semmel 

Glad you like the new association and that it makes sense. I've been thinking about it for too long now.

And good call on the specific event functions to replace the notification callback. It could inherit from `EventEmitter`and wrap it under a function as such:

``` javascript
DEA.notifications.onClose(function(notificationId) { ... });

DEA.notifications.onPrimaryButtonClicked(function(notificationId) { ... });
```

As for `progress` notification, I can't believe I missed it. Just saw it on the rich notifications app.

I was originally planning on implementing on implementing the `update` so that will come with the progress notification.

**Comment by adam-lynch** [comment]
:+1:

**Comment by eps90** [comment]
:+1: 
Something new with this issue?

**Comment by pbojinov** [comment]
@eps90 I currently don't have enough time to pursue this issue so its backlogged. Any help to tackle this would be great. PR are always welcomed.
