### ISSUE TITLE
Platform-independent

### ISSUE THREAD

**Issue by adam-lynch** [pbojinov/nodeifications#16]
FYI,  I'm going to create a PR like https://github.com/robrighter/nw-desktop-notifications/pull/7 where I'll switch grunt to gulp, remove the need for `.sh` file and use [node-webkit-builder](https://github.com/mllrsohn/node-webkit-builder).

**Comment by pbojinov** [comment]
That all sounds amazing :+1: 

The `.sh` build has been a pain point on Windows so I like the idea of platform independence

**Comment by adam-lynch** [comment]
Ok, I've done this. There's a problem though. I've already forked robrighter/nw-desktop-notifications and have unresolved PRs. Since this is a fork of the same project, it's awkward. I figured out how to manually create a second fork of the same repository (because you can't via GitHub itself) but there's no way to create a PR back to this repository via GitHub (even though I did set up the remotes correctly). 

I did try using [pullr](https://www.npmjs.org/package/pullr) to do it from the command-line but it [doesn't work because I've two-factor auth.](https://github.com/mojotech/pullr/issues/48) turned on.

The only way I can see around this is to add me as a collaborator to this project so I can commit directly onto a new branch and then create a PR from that branch to master.

To see the summary of changes, see [this PR](https://github.com/adam-lynch/nodeifications/pull/1) I accidentally created within my fork.

**Comment by pbojinov** [comment]
:+1: 

@adam-lynch sorry for the delay, just added you as a collaborator.

**Comment by adam-lynch** [comment]
@pbojinov thanks. I'll try push the commits tomorrow.
